# Generated by Django 6.0.7 on 2026-07-24 00:34

import django.db.models.deletion
import inventory.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=inventory.models._asset_code, editable=False, max_length=20, unique=True)),
                ('public_uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(help_text='Ej: Notebook Sala Docentes 3', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descripción breve del activo')),
                ('category', models.CharField(choices=[('PC', 'Computador de Escritorio'), ('LAPTOP', 'Notebook'), ('MONITOR', 'Monitor'), ('IMPRESORA', 'Impresora'), ('RED', 'Equipo de Red'), ('PROYECTOR', 'Proyector'), ('TELEFONO', 'Teléfono / Celular'), ('PERIFERICO', 'Periférico'), ('SERVIDOR', 'Servidor'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVO', 'En uso'), ('BODEGA', 'En bodega'), ('MANTENIMIENTO', 'En mantención'), ('BAJA', 'Dado de baja'), ('PRESTADO', 'Prestado')], db_index=True, default='ACTIVO', max_length=20)),
                ('serial_number', models.CharField(blank=True, db_index=True, max_length=100)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, help_text='Ej: Piso 2 - Oficina 204', max_length=150)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_until', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='asset_qr/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_responsible', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='inventory.asset')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_asset_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['status', 'category'], name='inventory_a_status_0d3db4_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['serial_number'], name='inventory_a_serial__4865f1_idx'),
        ),
    ]
