# Generated by Django 6.0.7 on 2026-07-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='N° de factura', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='legacy_id',
            field=models.CharField(blank=True, db_index=True, help_text="ID correlativo del Excel/GLPI original (columna 'Serie GLPI'). NO es unique: la planilla fuente tiene ids repetidos por error de tipeo, la deduplicación de reimportación se hace por (legacy_id + serial_number).", max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_company',
            field=models.CharField(blank=True, help_text='Proveedor/empresa de compra', max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='raw_type',
            field=models.CharField(blank=True, help_text='Tipo/categoría tal cual venía en la planilla original (texto libre, sin normalizar)', max_length=150),
        ),
    ]
