# Generated by Django 6.0.7 on 2026-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_asset_invoice_number_asset_legacy_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='responsible',
        ),
        migrations.RemoveField(
            model_name='assethistory',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='responsible_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='changed_by_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assethistory',
            name='changed_by_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
