# Generated by Django 6.0.7 on 2026-07-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red / Conectividad'), ('ACCESOS', 'Accesos y Cuentas'), ('OTRO', 'Otro'), ('RECLAMOS', 'Reclamos'), ('SUGERENCIAS', 'Sugerencias'), ('RESERVA DE SALA', 'Reserva de Sala')], max_length=20),
        ),
    ]
