# Generated by Django 6.0.7 on 2026-07-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red / Conectividad'), ('ACCESOS', 'Accesos y Cuentas'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
