# Generated by Django 6.0.7 on 2026-07-25 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('RED', 'Red / Conectividad'), ('ACCESOS', 'Accesos y Cuentas'), ('RESERVA_DE_SALAS', 'Reserva de Salas'), ('RECLAMOS', 'Reclamos'), ('SUGERENCIAS', 'Sugerencias'), ('OTRO', 'Otro')], max_length=20),
        ),
    ]
