# Generated by Django 6.0.7 on 2026-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_alter_ticket_category'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_assigne_8268c8_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_request_d7d4c7_idx',
        ),
        # Los RemoveField de los FKs viejos van ANTES que los AddField de
        # los campos planos nuevos: la columna DB de un ForeignKey usa por
        # default el nombre "<campo>_id" (ej. 'assigned_technician' ->
        # columna 'assigned_technician_id'), que es exactamente el mismo
        # nombre elegido para el nuevo campo plano — si el AddField corre
        # antes de que la columna vieja se elimine, SQLite falla con
        # "duplicate column name" al intentar crear una columna que ya
        # existe físicamente en la tabla.
        migrations.RemoveField(
            model_name='ticket',
            name='assigned_technician',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='requester',
        ),
        migrations.RemoveField(
            model_name='ticketattachment',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='ticketcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tickettimelog',
            name='technician',
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_technician_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_technician_username',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketattachment',
            name='uploaded_by_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='author_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='tickettimelog',
            name='technician_id',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tickettimelog',
            name='technician_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_technician_id', 'status'], name='tickets_tic_assigne_8268c8_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['requester_id'], name='tickets_tic_request_d7d4c7_idx'),
        ),
    ]
