# Generated by Django 6.0.7 on 2026-08-14 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_remove_ticket_tickets_tic_assigne_8268c8_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='requester_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requester_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='uploaded_by_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='author_username',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tickettimelog',
            name='technician_id',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='tickettimelog',
            name='technician_username',
            field=models.CharField(max_length=150),
        ),
    ]
