# Generated by Django 6.0.7 on 2026-08-28 22:49

from django.db import migrations, models


def _archive_priority(apps, schema_editor):
    """Archiva `Ticket.priority` en una tabla aparte antes de
    eliminarlo (ver el RemoveField más abajo). El campo se elimina a
    propósito — el SLA ya es plano y `TicketByPrioritySpec` no
    existe más — pero un `RemoveField` revertido (`migrate 0011`) NO
    restaura los valores originales: Django reconstruye la columna con
    su `default` ('MEDIA'), aplanando el histórico. Esta tabla es la
    única forma de recuperar la prioridad real de un ticket si hiciera
    falta revertir esta migración más adelante.

    Todo por SQL crudo (sin `apps.get_model`) y como PRIMERA operación
    de la migración a propósito: en SQLite, agregar un campo `unique`
    (el `external_message_id` de más abajo) obliga a reconstruir toda
    la tabla, y esa reconstrucción usa el estado final del modelo tal
    como lo ve el schema editor en ese momento — leer `priority` DESPUÉS
    de esas operaciones (aunque el `RemoveField` en sí venga después en
    la lista) puede encontrar la columna ya ausente. Archivar primero,
    antes de tocar la tabla para cualquier otra cosa, evita depender de
    ese detalle de implementación por backend."""
    schema_editor.execute(
        "CREATE TABLE IF NOT EXISTS tickets_priority_archive ("
        "ticket_id BIGINT PRIMARY KEY, priority VARCHAR(20) NOT NULL)"
    )
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT id, priority FROM tickets_ticket")
        rows = cursor.fetchall()
        for ticket_id, priority in rows:
            cursor.execute(
                "INSERT INTO tickets_priority_archive (ticket_id, priority) VALUES (%s, %s)",
                [ticket_id, priority],
            )


def _restore_priority_from_archive(apps, schema_editor):
    """Reverso de `_archive_priority`. Al revertir, Django procesa las
    operaciones en orden inverso: primero deshace el `RemoveField`
    (la columna `priority` vuelve a existir, poblada con el default
    'MEDIA'), y recién después llega acá — donde se pisa ese default
    con el valor real archivado, fila por fila, y se limpia la tabla
    de archivo."""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SELECT ticket_id, priority FROM tickets_priority_archive")
        rows = cursor.fetchall()
        for ticket_id, priority in rows:
            cursor.execute(
                "UPDATE tickets_ticket SET priority = %s WHERE id = %s", [priority, ticket_id],
            )
    schema_editor.execute("DROP TABLE IF EXISTS tickets_priority_archive")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_requester_id_and_more'),
    ]

    operations = [
        migrations.RunPython(_archive_priority, _restore_priority_from_archive),
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('subject_template', models.CharField(max_length=255)),
                ('body_template', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tickets_response_template',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_tic_status_b256f6_idx',
        ),
        migrations.AddField(
            model_name='ticket',
            name='external_message_id',
            field=models.CharField(blank=True, help_text='Message-ID del correo entrante que originó el ticket (idempotencia del poller).', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='requester_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_internal',
            field=models.BooleanField(default=False, help_text='Nota interna (solo Técnico/Admin) — nunca se reenvía por correo al solicitante.'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='tickets_tic_status_0e5646_idx'),
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='priority',
        ),
    ]
