# Generated by Django 6.0.7 on 2026-08-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_responsetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='external_message_id',
            field=models.CharField(blank=True, help_text='Message-ID del correo entrante que originó este comentario (idempotencia del poller — evita duplicar la respuesta si el mismo correo se reprocesa).', max_length=255, null=True, unique=True),
        ),
    ]
